[versions]
java = "25"
springBoot = "4.0.2"
dependencyManagement = "1.1.7"

springModulithBom = "2.0.1"
springDotenv = "5.1.0"
jjwt = "0.12.6"

[libraries]
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "springModulithBom" }

spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core" }
spring-modulith-starter-jpa = { module = "org.springframework.modulith:spring-modulith-starter-jpa" }

postgresql = { module = "org.postgresql:postgresql" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

lombok = { module = "org.projectlombok:lombok" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test" }
spring-boot-starter-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }

[bundles]
web-stack = [
    "spring-boot-starter-webmvc",
    "spring-boot-starter-validation",
    "spring-boot-starter-security"
]
database = [
    "spring-boot-starter-data-jpa",
    "spring-boot-starter-flyway",
    "flyway-database-postgresql",
    "postgresql"
]
modulith = [
    "spring-modulith-starter-core",
    "spring-modulith-starter-jpa"
]
testing = [
    "spring-boot-starter-data-jpa-test",
    "spring-boot-starter-flyway-test",
    "spring-boot-starter-security-test",
    "spring-boot-starter-webmvc-test",
    "spring-modulith-starter-test",
    "spring-boot-testcontainers",
    "testcontainers-postgresql"
]
development = ["spring-boot-devtools"]
jwt = ["jjwt-api", "jjwt-impl", "jjwt-jackson"]